### ISSUE TITLE
Роли пользователей

### ISSUE THREAD

**Issue by egorlutohin** [dicos/geneticist#37]
группы не нужны
permissions не нужны

Т.к. не используются, предлагаю удалить.

А вместо этого прикрутить какой-нибудь role based permission.

**Comment by dicos** [comment]
На текущий момент в разделе для мед. сестер нет ссылок на редактирование справочников. Редактировать справочники могут люди, у которых есть доступ в джанговскую админку. Так как людей будет много, то есть смысл создать 2 группы людей:
1-я будет иметь доступ только для редактирования справочников
2-я это главный генетик. Члены этой группы могут скрывать пациентов из базы данных.
