### ISSUE TITLE
Отчет по живым пациентам за период (место проживания)

### ISSUE THREAD

**Issue by egorlutohin** [dicos/geneticist#51]
В первом отчете (Отчет по живым пациентам за период), если выбирать "место проживания", то количество пациентов будет по нулям.

**Comment by dicos** [comment]
Исправил, во время проверки не подумал, что можно указать текущую дату

11.11.2013, 11:49, "egorlutohin" notifications@github.com:

> В первом отчете (Отчет по живым пациентам за период), если выбирать "место проживания", то количество пациентов будет по нулям.
> 
> —
> Reply to this email directly or view it on GitHub.

## 

С уважением, Дмитрий.
